### ISSUE TITLE
Investigate why fddev fails to allocate shared memory region for fd_net_quic.wksp

### ISSUE THREAD

**Issue by anoushk1234** [firedancer-io/firedancer#3607]
![image](https://github.com/user-attachments/assets/f003b994-1a8a-48da-817b-a23dae6ad8ae)

Version: v0.202.20016 

Config:
```toml
name = "fd-anoushk"
user = "ubuntu"

[development]
    sandbox = false
    [development.netns]
        enabled = true
[tiles.net]
    interface = "veth_test_xdp_0"

[rpc]
    port = 8899
    full_api = true
    private = true
```
