### ISSUE TITLE
README instructions to run fddev on 2 machines don't work

### ISSUE THREAD

**Issue by jda-dev** [firedancer-io/firedancer#4597]
Per README.md:

> The make run target runs the fddev dev command. This development command will ensure your system is configured correctly before creating a genesis block, some keys, a faucet, and then starting a validator on the local machine. fddev will use sudo to make privileged changes to system configuration where needed. If sudo is not available, you may need to run the command as root.
> By default fddev will create a new development cluster, if you wish to join this cluster with other validators, you can define [rpc.entrypoints] in the configuration file to point at your first validator and run fddev dev again.

These instructions alone don't seem to be enough to get the 2nd validator to join the cluster created by the first validator.

First validator:
`make -j run`

Second validator:
```
:/home/firedancer/firedancer# cat second_node.toml 
[gossip]
entrypoints = ["18.xx.xx.xx:8001"] 
:/home/firedancer/firedancer# ./build/native/gcc/bin/fddev dev --config second_node.toml 
```

The 2nd validator is at least able to talk to the first, in that it gets a shred version:
`fd1:[group]:agave validator/src/main.rs(443)[agave_validator::main]: obtained shred-version 6060 from 18.xx.xx.xx:8001`

And the first validator sees echos from the 2nd:
```
fd1:[group]:16   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 3.xx.xx.xx:35208
fd1:[group]:16   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 3.xx.xx.xx:35222
fd1:[group]:16   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 3.xx.xx.xx:35238
```

However, the 2nd validator fails to find an RPC server:
```
RPC Address       |Age(ms)| Node identifier                              | Version | RPC  |PubSub|ShredVer
------------------+-------+----------------------------------------------+---------+------+------+--------
RPC Enabled Nodes: 0
```

Eventually the 2nd validator exits for this reason:
```
ERR     03-21 10:03:51.147866 13941  f0   agave validator/src/bootstrap.rs(503): Failed to get RPC nodes: Unable to find any RPC peers. Consider checking system clock, removing `--no-port-check`, or adjusting `--known-validator ...` arguments as applicable
ERR     03-21 10:03:51.157002 13851  f0   pidns src/app/fdctl/run/run.c(414): tile agave:0 exited with code 1
```

Is there something else that needs to be done to make the first validator run RPC so that the cluster can actually come alive?

I tried also launching the first validator with a simple config `first_node.toml` like so:
```
[rpc]
 port = 8899
 bind_address = "0.0.0.0" 
 full_api = true
 private = false           
```
And launching with:
` ./build/native/gcc/bin/fddev dev --config first_node.toml `

But in that case the first node always fails with:
`ERR     03-21 10:13:08.500449 546    f12  10   gossip/src/cluster_info.rs(1473): Insert self failed: InsertFailed`

In fact, even if first_node.toml is blank the first node always gets InsertFailed.
So I'm thinking there's some other magic happening with `make -j run` that is not captured by doing `./build/native/gcc/bin/fddev dev`

So, is there a way to pass a config that turns on RPC when using `make -j run`?  Or is there a guide for how to use `fddev dev` directly in a way that approximates `make -j run`?  Or something else I'm missing entirely?  Thank you!

**Comment by anoushk1234** [comment]
@jda-dev the first validator should work using the dev command despite the InsertFailed, can you try using the config in fdctl/config/default.toml. `make -j run` uses this config.

I'm not sure why exactly the error occurs but when gossip throws InsertFailed it's usually because the message is outdated.

**Comment by jda-dev** [comment]
Thank you for the reply, if it is InsertFailed doesn't that mean that gossip failed to start?  In what sense is the first validator working if it gets InsertFailed?  I will try that other config. Thanks.

**Comment by jda-dev** [comment]
I've attempted running using a config based on fdctl/config/default.toml.  I am still facing the same issue: both validators boot, and the second validator is able to get the shred from the first validator.  However, it never finds the RPC from the first validtor and then it exits.

This is my bootstrap node config:
```toml
# Bootstrap Node Configuration
name = "fd1"
user = "firedancer"
scratch_directory = "/home/firedancer/.firedancer/{name}"
dynamic_port_range = "8900-9000"

[log]
path = "/home/firedancer/fd-cluster/bootstrap.log"
colorize = "auto"
level_logfile = "INFO"
level_stderr = "NOTICE"
level_flush = "WARNING"

[ledger]
path = "/home/firedancer/fd-cluster/ledger"
limit_size = 200_000_000

[gossip]
entrypoints = []
port_check = true
port = 8700
host = "52.14.178.171"  # Replace with your bootstrap node's public IP

[rpc]
port = 8899
full_api = true
private = false
bind_address = "0.0.0.0"
transaction_history = true

[snapshots]
enabled = true
incremental_snapshots = true
full_snapshot_interval_slots = 200
incremental_snapshot_interval_slots = 100
maximum_full_snapshots_to_retain = 2
maximum_incremental_snapshots_to_retain = 4
minimum_snapshot_download_speed = 10485760

[consensus]
identity_path = "/home/firedancer/fd-cluster/bootstrap-validator-keypair.json"
vote_account_path = "/home/firedancer/fd-cluster/bootstrap-vote-keypair.json"
snapshot_fetch = false
genesis_fetch = false
poh_speed_test = true
wait_for_vote_to_start_leader = false
os_network_limits_test = false
known_validators = []

[development]
bootstrap = true
sandbox = false
core_dump = true

[development.gossip]
allow_private_address = true
```

This is my second node config:
```toml
# Second Node Configuration
name = "fd2"
user = "firedancer"
scratch_directory = "/home/firedancer/.firedancer/{name}"
dynamic_port_range = "8900-9000"

[log]
path = "/home/firedancer/fd-cluster/second-node.log"
colorize = "auto"
level_logfile = "INFO"
level_stderr = "NOTICE"
level_flush = "WARNING"

[ledger]
path = "/home/firedancer/fd-cluster/ledger"
limit_size = 200_000_000

[gossip]
entrypoints = ["52.14.178.171:8700"]  # Replace with your bootstrap node's IP and port
port_check = true
port = 8800
host = "18.118.111.165"  # Replace with your second node's public IP

[rpc]
port = 8899
full_api = true
private = false
bind_address = "0.0.0.0"
transaction_history = true

[snapshots]
enabled = true
incremental_snapshots = true
full_snapshot_interval_slots = 200
incremental_snapshot_interval_slots = 100
maximum_full_snapshots_to_retain = 2
maximum_incremental_snapshots_to_retain = 4
minimum_snapshot_download_speed = 10485760

[consensus]
identity_path = "/home/firedancer/fd-cluster/second-identity.json"
vote_account_path = "/home/firedancer/fd-cluster/second-vote.json"
snapshot_fetch = true
genesis_fetch = false
poh_speed_test = true
wait_for_vote_to_start_leader = true
os_network_limits_test = false
known_validators = ["4XNZeUE4ARzKZVovLrk4FpsEyrSoGoAZLu8Tt24dEDDW"]  # You might want to add the bootstrap node's pubkey here

[development]
bootstrap = false
sandbox = false
core_dump = true

[development.gossip]
allow_private_address = true
```

In the boostrap node logs, it sees plenty of connections from the second:
```
INFO    2025-03-31 04:30:24.519393842 GMT+00  17784:18339  firedancer:ip-172-31-16-118:f12  fd1:[group]:19   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 18.118.111.165:47732
INFO    2025-03-31 04:30:24.594292590 GMT+00  17784:18339  firedancer:ip-172-31-16-118:f12  fd1:[group]:19   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 18.118.111.165:47734
INFO    2025-03-31 04:36:56.431189086 GMT+00  17784:18339  firedancer:ip-172-31-16-118:f12  fd1:[group]:19   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 18.118.111.165:43066
INFO    2025-03-31 04:36:56.462892806 GMT+00  17784:18339  firedancer:ip-172-31-16-118:f12  fd1:[group]:19   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 18.118.111.165:43082
INFO    2025-03-31 04:36:56.466110035 GMT+00  17784:18339  firedancer:ip-172-31-16-118:f12  fd1:[group]:19   net-utils/src/ip_echo_server.rs(73)[solana_net_utils::ip_echo_server]: connection from 18.118.111.165:43086
```

In the second node logs, it receives the shred version from bootstrap:
```
INFO    2025-03-31 04:38:01.374452286 GMT+00  15822:15827  firedancer:ip-172-31-18-163:f0   fd2:[group]:agave validator/src/main.rs(443)[agave_validator::main]: obtained shred-version 50480 from 52.14.178.171:8700
```

However the second node still never sees RPC from the first:
```
INFO    2025-03-31 04:43:02.259054196 GMT+00  15822:15827  firedancer:ip-172-31-18-163:f0   fd2:[group]:agave validator/src/bootstrap.rs(739)[agave_validator::bootstrap]: 
RPC Address       |Age(ms)| Node identifier                              | Version | RPC  |PubSub|ShredVer
------------------+-------+----------------------------------------------+---------+------+------+--------
RPC Enabled Nodes: 0
INFO    2025-03-31 04:43:02.259072596 GMT+00  15822:15827  firedancer:ip-172-31-18-163:f0   fd2:[group]:agave validator/src/bootstrap.rs(206)[agave_validator::bootstrap]: Searching for an RPC service with shred version 50480 (Retrying: Wait for known rpc peers)...
INFO    2025-03-31 04:43:02.259079166 GMT+00  15822:15827  firedancer:ip-172-31-18-163:f0   fd2:[group]:agave validator/src/bootstrap.rs(241)[agave_validator::bootstrap]: Total 0 RPC nodes found. 0 known, 0 blacklisted
ERR     2025-03-31 04:43:02.259093907 GMT+00  15822:15827  firedancer:ip-172-31-18-163:f0   fd2:[group]:agave validator/src/bootstrap.rs(503)[agave_validator::bootstrap]: Failed to get RPC nodes: Unable to find any RPC peers. Consider checking system clock, removing `--no-port-check`, or adjusting `--known-validator ...` arguments as applicable
```

Sometimes it also displays this, but still same result.
```
INFO    2025-03-31 05:47:55.827730836 GMT+00  16604:16747  firedancer:ip-172-31-18-163:f12  fd2:[group]:1    gossip/src/cluster_info.rs(1880)[solana_gossip::cluster_info]: 
IP Address        |Age(ms)| Node identifier                              | Version |Gossip|TPUvote| TPU  |TPUfwd| TVU  |TVU Q |ServeR|ShredVer
------------------+-------+----------------------------------------------+---------+------+-------+------+------+------+------+------+--------
18.118.111.165  me|  5008 | 8eWGJj68kmUERgWa6veFAgqQ9fDsW2x3aKWxu2sXKrZ  |0.101.20113| 8800 |  none | none | none | none | none | none | 50480
Nodes: 0
Spies: 1
```

Do you have any ideas or further things to debug?  Thanks.
Both are running from f484617408de6d9c1153615db3d90015860d706f .
