### ISSUE TITLE
fddev bench stops working after a while

### ISSUE THREAD

**Issue by r1cs** [firedancer-io/firedancer#5372]
config:
```toml
user = "ubuntu"
dynamic_port_range = "30500-31000"
[hugetlbfs]
        gigantic_page_threshold_mib = 1024
#[layout]
#    affinity = "9-36"
 #   agave_affinity = "38-63"
  #  net_tile_count = 1
  #  quic_tile_count = 1
   # verify_tile_count = 8
   # bank_tile_count = 6
    #shred_tile_count = 1
     #poh_tile_count=30

[ledger]
path = "/home/ubuntu/solana/ledger"
accounts_path = "/home/ubuntu/solana/accounts"
limit_size = 50_000_000

[snapshots]
path = "/home/ubuntu/solana/snapshot"
# snapshot_fetch = false

[tiles.metric]
        # The address to listen on.  By default, metrics are only
        # accessible from the local machine.  If you wish to expose them
        # to the network, you can change the listen address.
        #
        # The Firedancer team makes a best effort to secure the metrics
        # endpoint but exposing it to the internet from a production
        # validator is not recommended as it increases the attack
        # surface of the validator.
        prometheus_listen_address = "0.0.0.0"

        # The port to listen on for HTTP request for Prometheus metrics.
        # Firedancer serves metrics at a URI like 127.0.0.1:7999/metrics
        prometheus_listen_port = 7999
[tiles.gui]
        gui_listen_address = "0.0.0.0"

[gossip]
    entrypoints = [
      "entrypoint.mainnet-beta.solana.com:8001",
      "entrypoint2.mainnet-beta.solana.com:8001",
      "entrypoint3.mainnet-beta.solana.com:8001",
        "entrypoint4.mainnet-beta.solana.com:8001",
        "entrypoint5.mainnet-beta.solana.com:8001",
        "185.19.218.3:8000",
        "185.191.117.17:8000",
        "185.191.117.173:8001",
        "185.191.117.170:8001",
        "217.170.192.166:8001",
        "134.119.216.79:8001",
    ]

[consensus]
    identity_path = "/home/ubuntu/solana/jito-rpc-identity.json"
  #  expected_shred_version = 50093
  #  wait_for_vote_to_start_leader = false
#       poh_speed_test = false    
    known_validators = [
        "Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24",
        "7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2",
        "GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ",
        "CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S",
        "DB7DNWMVQASMFxcjkwdr4w4eg3NmfjWTk2rqFMMbrPLA",
        "CtvdyHYt8cMuGVHFarV2RADfoCdnrbd8e9jAsB225uMW",
        "3BeharBd3j4sKQp7Qze27JLQLd9AEEwGTX9TC7dXYSNw",
        "4VrjyXQT61WFSjuG3ehgqZUK1jqvYqB46veQbXLotq3n",
        "BCS95L5JHBWHvWkcEJBEF3BH5QHxKcPeaTgoYmHLvfFh",
        "2X7WoaXX9KPqNrNfvguhnwo3rjFPNsfw2t75fGjWRthz",
        "5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on",
        "dDzy5SR3AXdYWVqbDEkVFdvSPCtS9ihF5kJkHCtXoFs",
        "Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN",
        "eoKpUABi59aT4rR9HGS3LcMecfut9x7zJyodWWP43YQ",
        "9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv",
    ]

[rpc]
    bind_address = "0.0.0.0"
#    port_check = false
    port = 30000
    full_api = true
    private = true
  #  pubsub_enable_block_subscription = true
 #   pubsub_enable_vote_subscription = true
 #   only_known = true
 #   transaction_history = true

[geyser]
# Enable Geyser interface even if no Geyser configs are specified. [default: false]
# Passed to the Agave client with the `--geyser-plugin-always-enabled` argument.
    always_enabled = false

# Specify the configuration file for the Geyser plugin.
# Passed to the Agave client with the `--geyser-plugin-config` argument.
    config_path = "/home/ubuntu/solana/geyser.json"
```
In beginning, there is 80000 tps but then the tps gos lower and lower, at last but only have 2 tps.
